train: /home/erwan/Documents/TPS/2A/sudoku_python/datasets/images/train
val: /home/erwan/Documents/TPS/2A/sudoku_python/datasets/images/val

# Classes
nc: 9
names:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
